#version y release del Firmador Digital. Version debe ajustarse a la expresion regular [0-9]{1,2}.[0-9]{1,2}. Release debe ajustarse a la expresion regular [0-9]{1,2}
version=1.1
release=1
#url de descarga de updates
url_update=http://172.31.101.149:3000
#puerto del websocketserver
websocketserver_port=8025
#parametro de preaviso vencimiento de certificados. Debe ajustarse a la expresion regular [0-9]{1,2}
cantdias_preavisovencimientocertificado=20
#parametros para configurar servidor de timestamping. Si la url_TSA se deja vacia, no se agregara sello de tiempo a la firma.
#http://time.certum.pl/
url_TSA=http://timestamp.digicert.com
user_TSA=
password_TSA=
#url de callback definida por el organismo en su tramite de integracion con la PFDR
url_redirectfirmaremota=https://pfdr.sign.pjm.gob.ar
#url PFDR (Plataforma de firma digital remota)
url_firmadorpfdr=https://firmar.gob.ar
